name: Test Docked Image build

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test-image:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        scenario:
          - name: basic
            command: rails new /app
          - name: postgres
            command: rails new /app --database=postgresql
          - name: mysql
            command: rails new /app --database=mysql
          - name: trilogy
            command: rails new /app --database=trilogy
          - name: mariadb-mysql
            command: rails new /app --database=mariadb-mysql
          - name: mariadb-trilogy
            command: rails new /app --database=mariadb-trilogy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docked image
        run: |
          docker build -t rails-test-image:${{ github.sha }} .

      - name: Test rails new command in container
        run: |
          docker run --rm rails-test-image:${{ github.sha }} bash -c "\
            rails new /testapp && \
            cd /testapp && \
            bin/rails --version"

      - name: Run rails new - ${{ matrix.scenario.name }}
        run: |
          docker run --rm rails-test-image:${{ github.sha }} bash -c "
            set -e
            echo 'Testing: ${{ matrix.scenario.command }}'
            ${{ matrix.scenario.command }} && cd /app && bin/rails --version
            echo '✅ Success: ${{ matrix.scenario.command }}'
          "
